### ISSUE TITLE
 Are there any functions to perform image stitching in Android for React Native?

### ISSUE THREAD

**Issue by cavadibrahimli1** [lukaszkurantdev/react-native-fast-opencv#29]
Hi, I am working on a React Native project, and I need to perform image stitching on Android devices. Is there any existing function  (or a native Android solution) that can be used to achieve this?

 Any examples or guides would be greatly appreciated! Thank you.

**Comment by lukaszkurantdev** [comment]
Hi @cavadibrahimli1, support for the stitching module is currently outside the library. It is of course possible to use OpenCV for this purpose, but this would require:
- A customised OpenCV compilation containing the stitching module.
- Replacement of the cocoapod (iOS) or gradle module (Android) used in the application.
- Exposing the module code using the library API.

Due to the desire to keep the library as small as possible, more advanced modules are not available.

**Comment by cavadibrahimli1** [comment]
Are there any plans about adding this module in library in future in your mind?

**Comment by lukaszkurantdev** [comment]
I have no such plans at present, but the repository is open to pull requests.
